In [53]:
import numpy as np
import sympy as sym
import matplotlib.pyplot as plt

## Punto 1

In [54]:
def producto(A, B):
    tam_A = np.shape(A)
    tam_B = np.shape(B) 

    if tam_A[1] != tam_B[0]:
        print("Las matrices no se pueden multiplicar.")
        
    else:
        C = np.empty((tam_A[0], tam_B[1]))
        for filas in range(0,tam_A[0]):
            for col in range(0,tam_B[1]):
                C[filas,col] = np.dot(A[filas,:], B[:,col])
        return C

a)

In [55]:
a = np.array([[5, -4, -2],\
            [5, -5, 4],
             [2, 5, -4],
             [-5, 4, 3],
             [3, -4, -3]])

b=np.array([[5],
            [-2],
            [-3]])

In [56]:
producto(a,b)

array([[ 39.],
       [ 23.],
       [ 12.],
       [-42.],
       [ 32.]])

b)

In [57]:
a2 = np.array([[0, -1, -1, 3],\
            [5, -5, -2, 2],
             [1, 0, 4, 5]])

b2 = np.array([[0, -3],\
            [-2, -1],
             [3, -3],])

In [58]:
producto(a2, b2)

Las matrices no se pueden multiplicar.


c)

In [59]:
a3 = np.array([[2,-5,5,1],\
               [5,2,-7,-6],
               [-6,-1,7,-4],
               [5,4,1,-5]])

b3 = np.array([[0,4,-7,1,-6],\
               [-1,-6,-5,1,1],
               [2,-1,-6,5,-5],
               [-3,-6,6,3,5]])

In [60]:
producto(a3,b3)

array([[ 12.,  27., -13.,  25., -37.],
       [  2.,  51., -39., -46., -23.],
       [ 27.,  -1., -19.,  16., -20.],
       [ 13.,  25., -91.,  -1., -56.]])

## Punto 2

In [61]:
def reducir_a_triangular_superior(matriz):
    n = len(matriz)
    for i in range(n):
        pivot = matriz[i][i]
        if pivot != 0:
            matriz[i] = matriz[i] / pivot

        for j in range(i + 1, n):
            factor = matriz[j][i]
            matriz[j] = matriz[j] - factor * matriz[i]

    return matriz



In [62]:
def back_substitution(A, b):
    '''
    Args:
        A (np.array): Matriz de coeficientes triangular superior
        b (np.arra): vector de constantes
        
    '''

    n = np.shape(A)[0]

    x = np.zeros(n)

    for i in range(n-1,-1,-1):
        sum = b[i]
        for j in range(n-1,i,-1):
            sum -= A[i,j]*x[j]
        x[i] = sum/A[i,i]

    return x

In [63]:
def Gauss_Jordan(A,b):
    n = np.shape(A)[0]
    M = np.zeros(shape=(n,n+1))
    M[:,0:n] = A
    M[:,n] = b
    
    reducida =reducir_a_triangular_superior(M)
    resp = back_substitution(reducida[:,0:n], reducida[:,n])
    
    print(resp)
    

a.

In [64]:
A1 = np.array([[3,1,-1],\
            [1,-2,1],
             [4,-1,1],])

b1 = np.array([2,0,3])

In [65]:
Gauss_Jordan(A1,b1)

[0.71428571 0.85714286 1.        ]


b.

In [66]:
A2 = np.array([[1,1,1],\
            [0,-8,10],
             [4,-8,0],])

b2 = np.array([0,0,6])

In [67]:
Gauss_Jordan(A2,b2)

[ 0.71052632 -0.39473684 -0.31578947]


## Punto 3

In [68]:
x0=np.array([1,1,1])

A=np.array([[2,1,3],
           [1,2,3],
           [3,3,20]])

In [69]:
Ai=np.linalg.inv(A)

In [70]:
def vector(x0, A, k):
    x_n = x0
    for i in range(k-1):
        x_n = np.dot(A, x_n/np.linalg.norm(x_n))
        
    x_n1 = np.dot(A, x_n)
    
    resp = np.dot(x_n.T, x_n1) / np.dot(x_n.T, x_n )
    
    return np.abs(resp)

In [71]:
vector(x0, Ai, 4)

0.4999995679061639

In [72]:
x=sym.Symbol("k_11",real=True)
y =sym.Symbol("m1",real=True)