In [137]:
import numpy as np
import sympy as sym
import matplotlib.pyplot as plt


## Punto 1

In [138]:
def producto(A, B):
    tam_A = np.shape(A)
    tam_B = np.shape(B) 

    if tam_A[1] != tam_B[0]:
        print("Las matrices no se pueden multiplicar.")
        
    else:
        C = np.empty((tam_A[0], tam_B[1]))
        for filas in range(0,tam_A[0]):
            for col in range(0,tam_B[1]):
                C[filas,col] = np.dot(A[filas,:], B[:,col])
        return C

a)

In [139]:
a = np.array([[5, -4, -2],\
            [5, -5, 4],
             [2, 5, -4],
             [-5, 4, 3],
             [3, -4, -3]])

b=np.array([[5],
            [-2],
            [-3]])

In [140]:
producto(a,b)

array([[ 39.],
       [ 23.],
       [ 12.],
       [-42.],
       [ 32.]])

b)

In [141]:
a2 = np.array([[0, -1, -1, 3],\
            [5, -5, -2, 2],
             [1, 0, 4, 5]])

b2 = np.array([[0, -3],\
            [-2, -1],
             [3, -3],])

In [142]:
producto(a2, b2)

Las matrices no se pueden multiplicar.


c)

In [143]:
a3 = np.array([[2,-5,5,1],\
               [5,2,-7,-6],
               [-6,-1,7,-4],
               [5,4,1,-5]])

b3 = np.array([[0,4,-7,1,-6],\
               [-1,-6,-5,1,1],
               [2,-1,-6,5,-5],
               [-3,-6,6,3,5]])

In [144]:
producto(a3,b3)

array([[ 12.,  27., -13.,  25., -37.],
       [  2.,  51., -39., -46., -23.],
       [ 27.,  -1., -19.,  16., -20.],
       [ 13.,  25., -91.,  -1., -56.]])

## Punto 2

In [145]:
def reducir_a_triangular_superior(matriz):
    n = len(matriz)
    for i in range(n):
        pivot = matriz[i][i]
        if pivot != 0:
            matriz[i] = matriz[i] / pivot

        for j in range(i + 1, n):
            factor = matriz[j][i]
            matriz[j] = matriz[j] - factor * matriz[i]

    return matriz



In [146]:
def back_substitution(A, b):
    '''
    Args:
        A (np.array): Matriz de coeficientes triangular superior
        b (np.arra): vector de constantes
        
    '''

    n = np.shape(A)[0]

    x = np.zeros(n)

    for i in range(n-1,-1,-1):
        sum = b[i]
        for j in range(n-1,i,-1):
            sum -= A[i,j]*x[j]
        x[i] = sum/A[i,i]

    return x

In [147]:
def Gauss_Jordan(A,b):
    n = np.shape(A)[0]
    M = np.zeros(shape=(n,n+1))
    M[:,0:n] = A
    M[:,n] = b
    
    reducida =reducir_a_triangular_superior(M)
    resp = back_substitution(reducida[:,0:n], reducida[:,n])
    
    print(resp)
    

a.

In [148]:
A1 = np.array([[3,1,-1],\
            [1,-2,1],
             [4,-1,1],])

b1 = np.array([2,0,3])

In [149]:
Gauss_Jordan(A1,b1)

[0.71428571 0.85714286 1.        ]


b.

In [150]:
A2 = np.array([[1,1,1],\
            [0,-8,10],
             [4,-8,0],])

b2 = np.array([0,0,6])

In [151]:
Gauss_Jordan(A2,b2)

[ 0.71052632 -0.39473684 -0.31578947]


## Punto 3

In [152]:
x0=np.array([1,1,1])

In [153]:
def vector_sim(x0, A, k):
    #Funcion para trabajar con la matriz simbolica
    x_n = x0
    for i in range(k-1):
        #x_n = np.dot(A, x_n/(x_n[0]**2 + x_n[1]**2 +x_n[2]**2 )**0.5)   Con normalización
        x_n = np.dot(A, x_n)
    x_n1 = np.dot(A, x_n)
    
    resp = np.dot(x_n.T, x_n1) / np.dot(x_n.T, x_n )
    
    return np.abs(resp)

In [154]:
a1=sym.Symbol("k11")/sym.Symbol("m1")
a2=sym.Symbol("k12")/sym.Symbol("m1")
a3=sym.Symbol("k13")/sym.Symbol("m1")
a4=sym.Symbol("k21")/sym.Symbol("m2")
a5=sym.Symbol("k22")/sym.Symbol("m2")
a6=sym.Symbol("k23")/sym.Symbol("m2")
a7=sym.Symbol("k31")/sym.Symbol("m3")
a8=sym.Symbol("k32")/sym.Symbol("m3")
a9=sym.Symbol("k33")/sym.Symbol("m3")

k=sym.Symbol("k")

In [155]:
matriz = np.array([[a1,a2,a3],
                 [a4,a5,a6],
                 [a7,a8,a9]])

Frecuencia máxima de oscilación para $k=3$

In [156]:
valorp_max = vector_sim(x0, matriz, 3)

valor_max = sym.simplify(valorp_max.subs({"k11":-2*k, "k22":-2*k,"k33":-2*k,
               "k12":k,"k21":k, "k23":k, "k32":k,
               "k13":0, "k31":0}))

valor_max.subs( {"m1":1,"m2":1, "m3":1, "k":1} )



10/3

In [157]:
10/3

3.3333333333333335

Frecuencia mínima de oscilacilación para $k=2$

In [158]:
matriz_inv = sym.Matrix(matriz).inv()

In [159]:
vectorp_min=vector_sim(x0, matriz_inv, 2)

valor_min = sym.simplify(vectorp_min.subs({"k11":-2*k, "k22":-2*k,"k33":-2*k,
               "k12":k,"k21":k, "k23":k, "k32":k,
               "k13":0, "k31":0}))

valor_min.subs( {"m1":1,"m2":1, "m3":1, "k":1} )


29/17

In [160]:
29/17

1.7058823529411764