In [18]:
%matplotlib ipympl 
import numpy as np
import matplotlib.pyplot as plt
import time
import sympy as sym
from math import e
import matplotlib.animation as animation
from tqdm import tqdm

In [19]:
#Revisar matriz
A=np.array([[0.2, 0.1, 1, 1, 0],
            [0.1, 4, -1, 1, -1],
            [1, -1, 60, 0, -2],
            [1, 1, 0, 8, 4],
            [0, -1, -2, 4, 700]])
b=np.array([1,2,3,4,5])
x0=np.array([1,1,1,1,1])

In [20]:
np.dot(A,x0) 

array([  2.3,   3.1,  58. ,  14. , 701. ])

In [21]:
np.dot(A,x0) - b

array([  1.3,   1.1,  55. ,  10. , 696. ])

In [22]:
def i_dot(x,A):
    return np.dot(x.T, A, x) 

In [23]:
def desenso(A,b, x0, itmax=100, norma=0.01):
    rk = np.dot(A,x0)-b
    pk = -rk
    ak = np.dot( rk.T, pk)/ np.dot(pk.T, A, pk)
    xk= x0 + np.dot(ak, pk)

    d = np.max(np.abs(np.dot(A,rk) - b))
    it = 0
    #iteraciones
    ak = -( np.dot(rk.T,pk) )/np.dot(pk.T, A, pk )
    
    
    while d > norma and it < itmax:
        
        rk = rk - np.dot( ak,A, pk)
        
        Bk = np.dot(rk.T, A, pk)/np.dot(pk.T, A, pk)
        
        pk= -rk + np.dot(Bk, pk)

        ak = np.dot(rk.T, pk) / np.dot(pk.T, A, pk)                   #xk+1
        
        xk = xk + np.dot(ak, pk)   #xk+1
        
        d = np.max(np.abs(np.dot(A,rk) - b))
        it += 1
        print(d)
        
    print(it)
    return xk

In [24]:
desenso(A,b, x0)

2942259.4801277877
91216951.7859797
284382754.54215366
1218015405.76395
4791577967.804707
19246794815.6285
76906697033.9637
307707269649.82916
1230748597800.23
4923074871285.206
19692219005771.355
78768956501740.08
315075745529020.5
1260303062593307.5
5041212169896717.0
2.0164848760062664e+16
8.065939495977558e+16
3.2263757991957677e+17
1.2905503195978332e+18
5.162201278471806e+18
2.0648805113806758e+19
8.259522045530751e+19
3.303808818211496e+20
1.3215235272846787e+21
5.286094109138635e+21
2.114437643655462e+22
8.45775057462184e+22
3.3831002298487366e+23
1.3532400919394946e+24
5.412960367757981e+24
2.1651841471031923e+25
8.660736588412769e+25
3.4642946353651076e+26
1.385717854146043e+27
5.542871416584172e+27
2.217148566633669e+28
8.868594266534676e+28
3.54743770661387e+29
1.418975082645548e+30
5.675900330582192e+30
2.270360132232877e+31
9.081440528931508e+31
3.632576211572603e+32
1.4530304846290412e+33
5.812121938516165e+33
2.324848775406466e+34
9.299395101625864e+34
3.719758040650345

array([1.64967407e+135, 1.64967407e+135, 1.64967407e+135, 1.64967407e+135,
       1.64967407e+135])