In [38]:
%matplotlib ipympl 
import numpy as np
import matplotlib.pyplot as plt
import time
import sympy as sym
from math import e
import matplotlib.animation as animation
from tqdm import tqdm

In [39]:
#Revisar matriz
A=np.array([[0.2, 0.1, 1, 1, 0],
            [0.1, 4, -1, 1, -1],
            [1, -1, 60, 0, -2],
            [1, 1, 0, 8, 4],
            [0, -1, -2, 4, 700]])
b=np.array([1,2,3,4,5])
x0=np.array([1,1,1,1,1])

In [40]:
np.dot(A,x0) 

array([  2.3,   3.1,  58. ,  14. , 701. ])

In [41]:
x0.T

array([1, 1, 1, 1, 1])

In [42]:
def i_dot(x,A):
    return np.dot(x.T, A, x) 

In [54]:
def desenso(A,b, x0, itmax=100, norma=0.01):
    rk = np.dot(A,x0)-b
    pk = -rk
    ak = np.dot( rk.T, pk)/ np.dot(pk.T, A, pk)
    xk= x0 + np.dot(ak, pk)

    d = np.max(np.abs(rk))
    it = 0
    #iteraciones
    ak = -( np.dot(rk.T,pk) )/np.dot(pk.T, A, pk )
    
    
    while d > norma and it < itmax:
        
        rk = rk - np.dot( ak,A, pk)
        
        Bk = np.dot(rk.T, A, pk)/np.dot(pk.T, A, pk)
        
        pk= -rk + np.dot(Bk, pk)
        print(rk.T)
        print(pk)
        ak = np.dot(rk.T, pk) / np.dot(pk.T, A, pk)                   #xk+1
        
        xk = xk + np.dot(ak, pk)   #xk+1
        
        d = np.max(np.abs(rk))
        it += 1
        
        
    print(it)
    return xk

In [55]:
desenso(A,b, x0)

[14099.20740371  4988.26968972 49004.65391004 72647.41943751
  3563.84609435]
[2.05993768e+09 2.05994679e+09 2.05990277e+09 2.05987913e+09
 2.05994821e+09]
[ -15899.08065587 -195093.46815075 -116054.77197264 -119923.75647328
 -130234.93538883]
[-6.43477397e+10 -6.43475605e+10 -6.43476395e+10 -6.43476357e+10
 -6.43476253e+10]
[104093.09920015 605238.9254037  544171.12623327 650356.44206356
 404964.16421681]
[2.01284878e+11 2.01284376e+11 2.01284438e+11 2.01284331e+11
 2.01284577e+11]
[ -375875.71249555 -2596089.31129664 -2096734.03109513 -2430764.6600226
 -1735831.28499621]
[-8.61245131e+11 -8.61242911e+11 -8.61243410e+11 -8.61243076e+11
 -8.61243771e+11]
[ 1543999.40397702 10209225.10096589  8466884.61790317  9893719.25177292
  6827351.55733484]
[3.38887541e+12 3.38886674e+12 3.38886849e+12 3.38886706e+12
 3.38887013e+12]
[ -6135501.18099762 -41012031.12372959 -33787591.83386198
 -39404216.83678627 -27425378.79724687]
[-1.36116063e+13 -1.36115714e+13 -1.36115786e+13 -1.36115730e+13
 -1

array([1.64967407e+135, 1.64967407e+135, 1.64967407e+135, 1.64967407e+135,
       1.64967407e+135])